%% plate parameter
tic
plate.rho = [7700 7700];  % mass density of plate  kg/m^3
plate.E = [200e9 200e9];  % Young's Modulus of plate Pa
plate.niu = [0.3 0.3];  % Possion ratio of plate
plate.h = [0.005 0.005];  % Thickness of plate m
plate.d = 0.04;  % Distance between two plates m
plate.eta = 0;


%% lattice parameter
lattice.a = 0.042;  % Lattice constant m
lattice.a1 = [lattice.a 0];  % Lattice basis vector 1
lattice.a2 = [0 lattice.a];  % Lattice basis vector 2


%% propagation medium parameter
medium.rho = 1000;  % kg/m^3
medium.c0 = 1500;  % m/s


%% Incident wave parameter
incident.theta = 0*pi/180;  % Elevation Angle rad
incident.phi = 0*pi/180;  % Azimuth rad
incident.P0 = 10;  % Amplitute  Pa

freq = 10e3;  % frequeny Hz
lambda = medium.c0/freq;  % wavelength m
omega = 2*pi*freq;


%% Focus parameter
k0 = omega/medium.c0;  % wave number
focus.target = [0, NaN, 0.15];  % Set focal target point，NaN in Y means "Line Focus along Y-axis" ('1D_X')
focus.l_PML = lambda;  % set the length of PML as long as wavelength
focus.l_PML = lattice.a * round(focus.l_PML / lattice.a);  % Since the length of the PML must be an integer multiple of the lattice length, adjust its length.
focus.Lx_lens = lattice.a*17;
focus.Ly_lens = lattice.a;
focus.zeta_max = 8;

focus = ConfigureAcousticLens(focus, k0);
lattice.a1 = [focus.Lx_total, 0];
lattice.a2 = [0, focus.Ly_total];
% Directly scan the calculated values of m and k
% parasweep_result = load('Fe_2DOF_10kHz_a0.042h0.005d0.04.mat','k','m','tau_p','phi');
% [k_selected,m_selected,tau_selected,phi_selected,r_selected] = SelectOptimalResonators(focus, lattice, parasweep_result.k, parasweep_result.m, parasweep_result.tau_p, parasweep_result.phi);
% Read the m and k lists generated by COMSOL through finite element analysis and calculate the results.
data_file = 'E:\01 study\Plane Wave Expand Method\effective mass and stiffness\Rayleigh10kHz.mat';
para_list = computefromMKbyCOMSOL(data_file);
[para_selected] = SelectOptimalResonatorsCOMSOL(focus, lattice, para_list);


%% PWE core
M = 35;  % Order of plane wave cutoff


% In the resonator parameter matrix, while the number of rows for the position coordinates depends only on the number of resonators in a single lattice, the number of columns in the stiffness matrix and the mass matrix depends on the number of resonators in a single lattice, whereas the number of rows depends on the number of masses and springs within a single resonator.
%% Resonator parameter
resonator.N = length(para_selected.k);  % The number of resonators in a lattice
%        % Before optimization, only single-cell phase gradients were selected.
resonator.k = [para_selected.k;
               para_selected.k*0.5;
               para_selected.k];  % Elasticity Matrix of a Spring
resonator.m = [para_selected.m;
               para_selected.m];  % Mass Matrix of an Oscillator
resonator.r = para_selected.r;  % The position of the oscillator within the lattice
resonator.eta = [0];  % Dissipation Factor of a Resonator

[tau_power, tau_pressure, W2_Gout, k_zGout, G, feature] = PWE4PlateResonatorPlateDimless2DOF_PML(plate,resonator,lattice,medium,incident,M,freq,focus);
stl = 10*log10(1./tau_power);
tau_p = tau_power;
tau = abs(tau_pressure);
if angle(tau_pressure) > 0
    phi = angle(tau_pressure);
else
    phi = angle(tau_pressure)+2*pi;
end
W2_G = W2_Gout;
k_zG = k_zGout;


% % Plotting the Transmission Sound Field Region
x = -focus.Lx_total/2:0.005:focus.Lx_total/2;
y = -0.6:0.015:0.6;
z = 0:0.005:9*lambda;
[xx,zzx] = meshgrid(x,z);
[yy,zzy] = meshgrid(y,z);
field.x = xx;
% field.y = yy;
field.z = zzx;
for f = 1:length(freq)
    f0 = freq(f);
    omega = 2*pi*f0;
    k0 = omega/medium.c0;
    % Incident Wave Vector
    kx = k0 * sin(incident.theta) * cos(incident.phi);
    ky = k0 * sin(incident.theta) * sin(incident.phi);
    kz = k0 * cos(incident.theta);
    k = [kx ky kz];
    P_trG_numerator = 1i*medium.rho*omega^2;
%     field.y = zeros(size(field.y));
    P_tr = GenTransmissionField(W2_G, G, k_zG, k, field, P_trG_numerator, 0);
    figure("Name",sprintf("Transmission Field (freq = %d Hz, M = %d)",f0,M))
    surf(xx,zzx,abs(P_tr))
    view([-180 90])
    shading interp
    colormap jet
    xlabel('x/m')
    ylabel('z/m')
end


% Plot the sound pressure distribution along the focal line
linez_point = length(z);
linez = [zeros(linez_point,1) zeros(linez_point,1) z'];
linex_point = length(x);
linex = [x' zeros(linex_point,1) ones(linex_point,1)*focus.target(3)];
Ptr_line.z = GenTransmissionField(W2_G, G, k_zG, k, linez, P_trG_numerator, 1);
Ptr_line.x = GenTransmissionField(W2_G, G, k_zG, k, linex, P_trG_numerator, 1);
figure("Name",sprintf("Pressure on focal point line z (freq = %d Hz, M = %d)",f0,M))
plot(z,abs(Ptr_line.z))
figure("Name",sprintf("Pressure on focal point line x (freq = %d Hz, M = %d)",f0,M))
plot(x,abs(Ptr_line.x))


toc
% Note: passing 'resonator.k' instead of 'k1'
% [m_opt, k_opt, cost_opt] = AnomalousRefractionOptimization2DOF(plate, medium, incident, freq, M, lattice, resonator.m, resonator.k, resonator.r);
