function [para_selected] = SelectOptimalResonatorsCOMSOL(focus, lattice, para_list)
% SelectOptimalResonatorsCOMSOL maps the continuous phase profile generated by
% ConfigureAcousticLens to the discrete COMSOL geometry parameter sweep data,
% and automatically pads the PML boundary regions.

% Input: focus is the struct generated by ConfigurationAcousticLens;
%        lattice is a struct containing lattice parameters;
%        para_list is a struct containing geometry/effective/transmission parameters.
%        hmass, wmass, and wspring are geometry parameters; m and k are the
%        effective mass and stiffness; tau_p and phi are transmission data.

% Output:
%   para_selected is a struct containing all selected parameters and r.

disp(['Starting Inverse Design Selection for type: ', focus.type, '...']);
%% Determine Number of Active Units based on Lens Type
N_lens_x = round(focus.Lx_lens/lattice.a);
N_lens_y = round(focus.Ly_lens/lattice.a);
if mod(N_lens_x, 2) == 0
    N_lens_x = N_lens_x + 1;
end
if mod(N_lens_y, 2) == 0
    N_lens_y = N_lens_y + 1;
end
if strcmp(focus.type, '1D_Y')
    N_lens_x = 1;
end
if strcmp(focus.type, '1D_X')
    N_lens_y = 1;
end

%% Generate Spatial Coordinates for Active Lens
x_coords = linspace(-focus.Lx_lens/2+lattice.a/2, focus.Lx_lens/2-lattice.a/2, N_lens_x);
y_coords = linspace(-focus.Ly_lens/2+lattice.a/2, focus.Ly_lens/2-lattice.a/2, N_lens_y);
if N_lens_x == 1, x_coords = 0; end
if N_lens_y == 1, y_coords = 0; end
[X_grid, Y_grid] = meshgrid(x_coords, y_coords);

%% Calculate Target Phase and Optimize the Phase Origin
target_phase_continuous = focus.phase_func(X_grid, Y_grid);
min_transmission_threshold = 0.7;
[target_phase_wrapped, phase_offset] = AutoPhaseOptimal(...
    target_phase_continuous, para_list.phi, para_list.tau_p, min_transmission_threshold);

%% Inverse Selection Loop (Map theory to physical datasets)
valid_idx = para_list.tau_p >= min_transmission_threshold;
if ~any(valid_idx, 'all')
    warning('The transmission coefficient can not meet the threshold (>%d).', min_transmission_threshold);
    valid_idx = true(size(para_list.tau_p));
end
field_names = fieldnames(para_list);
for i = 1:length(field_names)
    para_selected.(field_names{i}) = zeros(N_lens_y, N_lens_x);
end
for iy = 1:N_lens_y
    for ix = 1:N_lens_x
        target = target_phase_wrapped(iy,ix);
        phase_error = abs(angle(exp(1i*(para_list.phi-target))));
        phase_error(~valid_idx) = inf;
        [~, min_idx] = min(phase_error);
        for i = 1:length(field_names)
            parameter = para_list.(field_names{i});
            if isvector(parameter)
                para_selected.(field_names{i})(iy,ix) = parameter(min_idx);
            end
        end
    end
end

%% Automatically Pad the Structure for PML Boundary Impedance Matching
N_PML_units = round(focus.l_PML/lattice.a);
for i = 1:length(field_names)
    parameter = para_selected.(field_names{i});
    if ~isvector(para_list.(field_names{i})), continue; end
    if strcmp(focus.type, '1D_X') || strcmp(focus.type, '2D')
        parameter = [repmat(parameter(:,1),1,N_PML_units), parameter, repmat(parameter(:,end),1,N_PML_units)];
    end
    if strcmp(focus.type, '1D_Y') || strcmp(focus.type, '2D')
        parameter = [repmat(parameter(1,:),N_PML_units,1); parameter; repmat(parameter(end,:),N_PML_units,1)];
    end
    para_selected.(field_names{i}) = parameter;
end

%% Calculate Total Metacell Coordinates and Format for Output
[Total_Ny, Total_Nx] = size(para_selected.m);
if strcmp(focus.type, '1D_X') || strcmp(focus.type, '2D')
    Lx_total_metacell = focus.Lx_lens+2*focus.l_PML;
else
    Lx_total_metacell = focus.Lx_lens;
end
if strcmp(focus.type, '1D_Y') || strcmp(focus.type, '2D')
    Ly_total_metacell = focus.Ly_lens+2*focus.l_PML;
else
    Ly_total_metacell = focus.Ly_lens;
end
x_total = linspace(-Lx_total_metacell/2+lattice.a/2, Lx_total_metacell/2-lattice.a/2, Total_Nx);
y_total = linspace(-Ly_total_metacell/2+lattice.a/2, Ly_total_metacell/2-lattice.a/2, Total_Ny);
if Total_Nx == 1, x_total = 0; end
if Total_Ny == 1, y_total = 0; end
[X_total, Y_total] = meshgrid(x_total, y_total);
para_selected.r = [reshape(X_total.',[],1), reshape(Y_total.',[],1)];
para_selected.phase_offset = phase_offset;
disp(['Inverse Design Complete! Generated parameters for ', num2str(numel(para_selected.m)), ' total metacell units.']);
end
